development:
  adapter: postgresql
  encoding: unicode
  database: val_db_development
  pool: 5
  username: val_user
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: val_db_test
  pool: 5
  username: val_user
  password: password1